name: CI

on:
  workflow_call:

jobs:
  run-common:
    name: Run common setup and tooling
    uses: kinetech-labs/.github/.github/workflows/common-setup.yml@main

  notify:
    name: Notify
    needs: [run-common]
    if: always()

    uses: kinetech-labs/.github/.github/workflows/notify.yml@main

    with:
      status: ${{ needs.run-common.result == 'success' && 'success' || 'failure' }}
      title: "CI"
      description: ${{ needs.run-common.result == 'success' && 'CI completed successfully.' || 'CI failed.' }}
      url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

    secrets:
      webhook: ${{ secrets.DISCORD_AUTOMATION_WEBHOOK }}
