name: PR Checks

on:
  workflow_call:

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Check branch name
        run: |
          echo "Branch: $GITHUB_HEAD_REF"

          if [[ "$GITHUB_HEAD_REF" == "main" ]]; then
            echo "❌ Invalid branch name"
            exit 1
          fi

      - name: Ensure PR is not empty
        run: |
          if [ -z "${{ github.event.pull_request.title }}" ]; then
            echo "❌ PR title missing"
            exit 1
          fi

  notify:
    name: Notify
    needs: [validate-pr]
    if: always()

    uses: kinetech-labs/.github/.github/workflows/notify.yml@main

    with:
      status: ${{ needs.validate-pr.result == 'success' && 'success' || 'failure' }}
      title: "Pull Request Validation"
      description: ${{ needs.validate-pr.result == 'success' && 'PR validation passed.' || 'PR validation failed.' }}
      url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

    secrets:
      webhook: ${{ secrets.DISCORD_AUTOMATION_WEBHOOK }}
